---
dataset_load:
  org: "wmt19"
  lang: "en-de"

dataset_save: "data_dummy/en-de/"

method:
  - Loader:load
  - Dummy:test
  - Loader:save

# example parameters
epochs: 50
dimensions:
  - 5
  - 30
  - 50
  - 20
batch_size: 32